import streamlit as st
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px
import shap
from sklearn.ensemble import RandomForestRegressor, GradientBoostingRegressor, AdaBoostRegressor
from sklearn.linear_model import LinearRegression, Ridge, Lasso
from sklearn.svm import SVR
from sklearn.tree import DecisionTreeRegressor
from sklearn.neighbors import KNeighborsRegressor
from sklearn.cluster import KMeans
from sklearn.decomposition import PCA
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
import warnings
warnings.filterwarnings('ignore')

st.set_page_config(page_title='🚀 Ultra AI Web App', layout='wide')
st.title('🌟 Ultra AI Student Score & ML Web App')

NUM_ROWS = 5000
np.random.seed(42)
data_dict = {}
data_dict['Feature_1'] = np.random.randint(0, 100, NUM_ROWS)
data_dict['Feature_2'] = np.random.randint(0, 100, NUM_ROWS)
data_dict['Feature_3'] = np.random.randint(0, 100, NUM_ROWS)
data_dict['Feature_4'] = np.random.randint(0, 100, NUM_ROWS)
data_dict['Feature_5'] = np.random.randint(0, 100, NUM_ROWS)
data_dict['Feature_6'] = np.random.randint(0, 100, NUM_ROWS)
data_dict['Feature_7'] = np.random.randint(0, 100, NUM_ROWS)
data_dict['Feature_8'] = np.random.randint(0, 100, NUM_ROWS)
data_dict['Feature_9'] = np.random.randint(0, 100, NUM_ROWS)
data_dict['Feature_10'] = np.random.randint(0, 100, NUM_ROWS)
data_dict['Feature_11'] = np.random.randint(0, 100, NUM_ROWS)
data_dict['Feature_12'] = np.random.randint(0, 100, NUM_ROWS)
data_dict['Feature_13'] = np.random.randint(0, 100, NUM_ROWS)
data_dict['Feature_14'] = np.random.randint(0, 100, NUM_ROWS)
data_dict['Feature_15'] = np.random.randint(0, 100, NUM_ROWS)
data_dict['Feature_16'] = np.random.randint(0, 100, NUM_ROWS)
data_dict['Feature_17'] = np.random.randint(0, 100, NUM_ROWS)
data_dict['Feature_18'] = np.random.randint(0, 100, NUM_ROWS)
data_dict['Feature_19'] = np.random.randint(0, 100, NUM_ROWS)
data_dict['Feature_20'] = np.random.randint(0, 100, NUM_ROWS)
data_dict['Feature_21'] = np.random.randint(0, 100, NUM_ROWS)
data_dict['Feature_22'] = np.random.randint(0, 100, NUM_ROWS)
data_dict['Feature_23'] = np.random.randint(0, 100, NUM_ROWS)
data_dict['Feature_24'] = np.random.randint(0, 100, NUM_ROWS)
data_dict['Feature_25'] = np.random.randint(0, 100, NUM_ROWS)
data_dict['Feature_26'] = np.random.randint(0, 100, NUM_ROWS)
data_dict['Feature_27'] = np.random.randint(0, 100, NUM_ROWS)
data_dict['Feature_28'] = np.random.randint(0, 100, NUM_ROWS)
data_dict['Feature_29'] = np.random.randint(0, 100, NUM_ROWS)
data_dict['Feature_30'] = np.random.randint(0, 100, NUM_ROWS)
data_dict['Feature_31'] = np.random.randint(0, 100, NUM_ROWS)
data_dict['Feature_32'] = np.random.randint(0, 100, NUM_ROWS)
data_dict['Feature_33'] = np.random.randint(0, 100, NUM_ROWS)
data_dict['Feature_34'] = np.random.randint(0, 100, NUM_ROWS)
data_dict['Feature_35'] = np.random.randint(0, 100, NUM_ROWS)
data_dict['Feature_36'] = np.random.randint(0, 100, NUM_ROWS)
data_dict['Feature_37'] = np.random.randint(0, 100, NUM_ROWS)
data_dict['Feature_38'] = np.random.randint(0, 100, NUM_ROWS)
data_dict['Feature_39'] = np.random.randint(0, 100, NUM_ROWS)
data_dict['Feature_40'] = np.random.randint(0, 100, NUM_ROWS)
data_dict['Feature_41'] = np.random.randint(0, 100, NUM_ROWS)
data_dict['Feature_42'] = np.random.randint(0, 100, NUM_ROWS)
data_dict['Feature_43'] = np.random.randint(0, 100, NUM_ROWS)
data_dict['Feature_44'] = np.random.randint(0, 100, NUM_ROWS)
data_dict['Feature_45'] = np.random.randint(0, 100, NUM_ROWS)
data_dict['Feature_46'] = np.random.randint(0, 100, NUM_ROWS)
data_dict['Feature_47'] = np.random.randint(0, 100, NUM_ROWS)
data_dict['Feature_48'] = np.random.randint(0, 100, NUM_ROWS)
data_dict['Feature_49'] = np.random.randint(0, 100, NUM_ROWS)
data_dict['Feature_50'] = np.random.randint(0, 100, NUM_ROWS)
data_dict['Score'] = np.random.randint(0, 100, NUM_ROWS)
data = pd.DataFrame(data_dict)

st.sidebar.header('Navigation')
menu = ['Home', 'Predict', 'Data Analysis', 'AI Explainability', 'Simulation', 'Batch Predictions', 'Clustering', 'PCA', 'Extra Visuals']
choice = st.sidebar.selectbox('Choose Page', menu)

features = [f'Feature_{i}' for i in range(1, NUM_FEATURES+1)]
target = 'Score'

models = []
models.append(('RF_1', RandomForestRegressor(n_estimators=50, random_state=42)))
models.append(('RF_2', RandomForestRegressor(n_estimators=50, random_state=42)))
models.append(('RF_3', RandomForestRegressor(n_estimators=50, random_state=42)))
models.append(('RF_4', RandomForestRegressor(n_estimators=50, random_state=42)))
models.append(('RF_5', RandomForestRegressor(n_estimators=50, random_state=42)))
models.append(('RF_6', RandomForestRegressor(n_estimators=50, random_state=42)))
models.append(('RF_7', RandomForestRegressor(n_estimators=50, random_state=42)))
models.append(('RF_8', RandomForestRegressor(n_estimators=50, random_state=42)))
models.append(('RF_9', RandomForestRegressor(n_estimators=50, random_state=42)))
models.append(('RF_10', RandomForestRegressor(n_estimators=50, random_state=42)))
models.append(('RF_11', RandomForestRegressor(n_estimators=50, random_state=42)))
models.append(('RF_12', RandomForestRegressor(n_estimators=50, random_state=42)))
models.append(('RF_13', RandomForestRegressor(n_estimators=50, random_state=42)))
models.append(('RF_14', RandomForestRegressor(n_estimators=50, random_state=42)))
models.append(('RF_15', RandomForestRegressor(n_estimators=50, random_state=42)))
models.append(('RF_16', RandomForestRegressor(n_estimators=50, random_state=42)))
models.append(('RF_17', RandomForestRegressor(n_estimators=50, random_state=42)))
models.append(('RF_18', RandomForestRegressor(n_estimators=50, random_state=42)))
models.append(('RF_19', RandomForestRegressor(n_estimators=50, random_state=42)))
models.append(('RF_20', RandomForestRegressor(n_estimators=50, random_state=42)))
models.append(('RF_21', RandomForestRegressor(n_estimators=50, random_state=42)))
models.append(('RF_22', RandomForestRegressor(n_estimators=50, random_state=42)))
models.append(('RF_23', RandomForestRegressor(n_estimators=50, random_state=42)))
models.append(('RF_24', RandomForestRegressor(n_estimators=50, random_state=42)))
models.append(('RF_25', RandomForestRegressor(n_estimators=50, random_state=42)))
models.append(('RF_26', RandomForestRegressor(n_estimators=50, random_state=42)))
models.append(('RF_27', RandomForestRegressor(n_estimators=50, random_state=42)))
models.append(('RF_28', RandomForestRegressor(n_estimators=50, random_state=42)))
models.append(('RF_29', RandomForestRegressor(n_estimators=50, random_state=42)))
models.append(('RF_30', RandomForestRegressor(n_estimators=50, random_state=42)))
models.append(('RF_31', RandomForestRegressor(n_estimators=50, random_state=42)))
models.append(('RF_32', RandomForestRegressor(n_estimators=50, random_state=42)))
models.append(('RF_33', RandomForestRegressor(n_estimators=50, random_state=42)))
models.append(('RF_34', RandomForestRegressor(n_estimators=50, random_state=42)))
models.append(('RF_35', RandomForestRegressor(n_estimators=50, random_state=42)))
models.append(('RF_36', RandomForestRegressor(n_estimators=50, random_state=42)))
models.append(('RF_37', RandomForestRegressor(n_estimators=50, random_state=42)))
models.append(('RF_38', RandomForestRegressor(n_estimators=50, random_state=42)))
models.append(('RF_39', RandomForestRegressor(n_estimators=50, random_state=42)))
models.append(('RF_40', RandomForestRegressor(n_estimators=50, random_state=42)))
models.append(('RF_41', RandomForestRegressor(n_estimators=50, random_state=42)))
models.append(('RF_42', RandomForestRegressor(n_estimators=50, random_state=42)))
models.append(('RF_43', RandomForestRegressor(n_estimators=50, random_state=42)))
models.append(('RF_44', RandomForestRegressor(n_estimators=50, random_state=42)))
models.append(('RF_45', RandomForestRegressor(n_estimators=50, random_state=42)))
models.append(('RF_46', RandomForestRegressor(n_estimators=50, random_state=42)))
models.append(('RF_47', RandomForestRegressor(n_estimators=50, random_state=42)))
models.append(('RF_48', RandomForestRegressor(n_estimators=50, random_state=42)))
models.append(('RF_49', RandomForestRegressor(n_estimators=50, random_state=42)))
models.append(('RF_50', RandomForestRegressor(n_estimators=50, random_state=42)))
models.append(('RF_51', RandomForestRegressor(n_estimators=50, random_state=42)))
models.append(('RF_52', RandomForestRegressor(n_estimators=50, random_state=42)))
models.append(('RF_53', RandomForestRegressor(n_estimators=50, random_state=42)))
models.append(('RF_54', RandomForestRegressor(n_estimators=50, random_state=42)))
models.append(('RF_55', RandomForestRegressor(n_estimators=50, random_state=42)))
models.append(('RF_56', RandomForestRegressor(n_estimators=50, random_state=42)))
models.append(('RF_57', RandomForestRegressor(n_estimators=50, random_state=42)))
models.append(('RF_58', RandomForestRegressor(n_estimators=50, random_state=42)))
models.append(('RF_59', RandomForestRegressor(n_estimators=50, random_state=42)))
models.append(('RF_60', RandomForestRegressor(n_estimators=50, random_state=42)))
models.append(('RF_61', RandomForestRegressor(n_estimators=50, random_state=42)))
models.append(('RF_62', RandomForestRegressor(n_estimators=50, random_state=42)))
models.append(('RF_63', RandomForestRegressor(n_estimators=50, random_state=42)))
models.append(('RF_64', RandomForestRegressor(n_estimators=50, random_state=42)))
models.append(('RF_65', RandomForestRegressor(n_estimators=50, random_state=42)))
models.append(('RF_66', RandomForestRegressor(n_estimators=50, random_state=42)))
models.append(('RF_67', RandomForestRegressor(n_estimators=50, random_state=42)))
models.append(('RF_68', RandomForestRegressor(n_estimators=50, random_state=42)))
models.append(('RF_69', RandomForestRegressor(n_estimators=50, random_state=42)))
models.append(('RF_70', RandomForestRegressor(n_estimators=50, random_state=42)))
models.append(('RF_71', RandomForestRegressor(n_estimators=50, random_state=42)))
models.append(('RF_72', RandomForestRegressor(n_estimators=50, random_state=42)))
models.append(('RF_73', RandomForestRegressor(n_estimators=50, random_state=42)))
models.append(('RF_74', RandomForestRegressor(n_estimators=50, random_state=42)))
models.append(('RF_75', RandomForestRegressor(n_estimators=50, random_state=42)))
models.append(('RF_76', RandomForestRegressor(n_estimators=50, random_state=42)))
models.append(('RF_77', RandomForestRegressor(n_estimators=50, random_state=42)))
models.append(('RF_78', RandomForestRegressor(n_estimators=50, random_state=42)))
models.append(('RF_79', RandomForestRegressor(n_estimators=50, random_state=42)))
models.append(('RF_80', RandomForestRegressor(n_estimators=50, random_state=42)))
models.append(('RF_81', RandomForestRegressor(n_estimators=50, random_state=42)))
models.append(('RF_82', RandomForestRegressor(n_estimators=50, random_state=42)))
models.append(('RF_83', RandomForestRegressor(n_estimators=50, random_state=42)))
models.append(('RF_84', RandomForestRegressor(n_estimators=50, random_state=42)))
models.append(('RF_85', RandomForestRegressor(n_estimators=50, random_state=42)))
models.append(('RF_86', RandomForestRegressor(n_estimators=50, random_state=42)))
models.append(('RF_87', RandomForestRegressor(n_estimators=50, random_state=42)))
models.append(('RF_88', RandomForestRegressor(n_estimators=50, random_state=42)))
models.append(('RF_89', RandomForestRegressor(n_estimators=50, random_state=42)))
models.append(('RF_90', RandomForestRegressor(n_estimators=50, random_state=42)))
models.append(('RF_91', RandomForestRegressor(n_estimators=50, random_state=42)))
models.append(('RF_92', RandomForestRegressor(n_estimators=50, random_state=42)))
models.append(('RF_93', RandomForestRegressor(n_estimators=50, random_state=42)))
models.append(('RF_94', RandomForestRegressor(n_estimators=50, random_state=42)))
models.append(('RF_95', RandomForestRegressor(n_estimators=50, random_state=42)))
models.append(('RF_96', RandomForestRegressor(n_estimators=50, random_state=42)))
models.append(('RF_97', RandomForestRegressor(n_estimators=50, random_state=42)))
models.append(('RF_98', RandomForestRegressor(n_estimators=50, random_state=42)))
models.append(('RF_99', RandomForestRegressor(n_estimators=50, random_state=42)))
models.append(('RF_100', RandomForestRegressor(n_estimators=50, random_state=42)))
for name, model in models:
    model.fit(data[features], data[target])

if choice == 'Home':
    st.markdown('Welcome to the Ultra AI Student Score Web App with 100+ models!')

elif choice == 'Predict':
    st.header('Predict Your Score')
    val_1 = st.slider('Feature 1', 0, 100, 50)
    val_2 = st.slider('Feature 2', 0, 100, 50)
    val_3 = st.slider('Feature 3', 0, 100, 50)
    val_4 = st.slider('Feature 4', 0, 100, 50)
    val_5 = st.slider('Feature 5', 0, 100, 50)
    val_6 = st.slider('Feature 6', 0, 100, 50)
    val_7 = st.slider('Feature 7', 0, 100, 50)
    val_8 = st.slider('Feature 8', 0, 100, 50)
    val_9 = st.slider('Feature 9', 0, 100, 50)
    val_10 = st.slider('Feature 10', 0, 100, 50)
    val_11 = st.slider('Feature 11', 0, 100, 50)
    val_12 = st.slider('Feature 12', 0, 100, 50)
    val_13 = st.slider('Feature 13', 0, 100, 50)
    val_14 = st.slider('Feature 14', 0, 100, 50)
    val_15 = st.slider('Feature 15', 0, 100, 50)
    val_16 = st.slider('Feature 16', 0, 100, 50)
    val_17 = st.slider('Feature 17', 0, 100, 50)
    val_18 = st.slider('Feature 18', 0, 100, 50)
    val_19 = st.slider('Feature 19', 0, 100, 50)
    val_20 = st.slider('Feature 20', 0, 100, 50)
    val_21 = st.slider('Feature 21', 0, 100, 50)
    val_22 = st.slider('Feature 22', 0, 100, 50)
    val_23 = st.slider('Feature 23', 0, 100, 50)
    val_24 = st.slider('Feature 24', 0, 100, 50)
    val_25 = st.slider('Feature 25', 0, 100, 50)
    val_26 = st.slider('Feature 26', 0, 100, 50)
    val_27 = st.slider('Feature 27', 0, 100, 50)
    val_28 = st.slider('Feature 28', 0, 100, 50)
    val_29 = st.slider('Feature 29', 0, 100, 50)
    val_30 = st.slider('Feature 30', 0, 100, 50)
    val_31 = st.slider('Feature 31', 0, 100, 50)
    val_32 = st.slider('Feature 32', 0, 100, 50)
    val_33 = st.slider('Feature 33', 0, 100, 50)
    val_34 = st.slider('Feature 34', 0, 100, 50)
    val_35 = st.slider('Feature 35', 0, 100, 50)
    val_36 = st.slider('Feature 36', 0, 100, 50)
    val_37 = st.slider('Feature 37', 0, 100, 50)
    val_38 = st.slider('Feature 38', 0, 100, 50)
    val_39 = st.slider('Feature 39', 0, 100, 50)
    val_40 = st.slider('Feature 40', 0, 100, 50)
    val_41 = st.slider('Feature 41', 0, 100, 50)
    val_42 = st.slider('Feature 42', 0, 100, 50)
    val_43 = st.slider('Feature 43', 0, 100, 50)
    val_44 = st.slider('Feature 44', 0, 100, 50)
    val_45 = st.slider('Feature 45', 0, 100, 50)
    val_46 = st.slider('Feature 46', 0, 100, 50)
    val_47 = st.slider('Feature 47', 0, 100, 50)
    val_48 = st.slider('Feature 48', 0, 100, 50)
    val_49 = st.slider('Feature 49', 0, 100, 50)
    val_50 = st.slider('Feature 50', 0, 100, 50)
    input_df = pd.DataFrame([{f'Feature_{i}': val_{i} for i in range(1, NUM_FEATURES+1)}])
    if st.button('Predict'):
